apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitops.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  GITOPS_SERVICE_HTTP_BIND: {{.Values.GITOPS_SERVICE_HTTP_BIND | quote}}
  GITOPS_SERVICE_HTTP_HOST: https://{{.Values.BASE}}.harness.io/{{.Values.CLUSTER}}/gitops
  AGENT_GRPC_AUTHORITY: {{.Values.domainVersion}}{{.Values.domainPrefix}}gitops-grpc-{{.Values.BASE}}.harness.io
  AGENT_GRPC_TARGET: {{.Values.BASE}}.harness.io:443
  GITOPS_SERVICE_HTTP_ACME: {{.Values.GITOPS_SERVICE_HTTP_ACME | quote}}
  GITOPS_SERVICE_MONGODB_DB_NAME: {{.Values.GITOPS_SERVICE_MONGODB_DB_NAME | quote}}
  GITOPS_SERVICE_MONGODB_ENABLE_REFLECTION: {{.Values.GITOPS_SERVICE_MONGODB_ENABLE_REFLECTION | quote}}
  GITOPS_SERVICE_TIMESCALE_DB_NAME: {{.Values.GITOPS_SERVICE_TIMESCALE_DB_NAME | quote}}
  GITOPS_SERVICE_TIMESCALE_LOG_LEVEL: {{.Values.GITOPS_SERVICE_TIMESCALE_LOG_LEVEL | quote}}
  REDIS_ENDPOINT: {{.Values.REDIS_ENDPOINT | quote}}
  REDIS_PASSWORD: {{.Values.REDIS_PASSWORD | quote}}
  REDIS_SSL_ENABLED: {{.Values.REDIS_SSL_ENABLED}}
  REDIS_SSL_CA_CERT_PATH: {{.Values.REDIS_SSL_CA_CERT_PATH | quote }}
  EVENTS_FRAMEWORK_ENV_NAMESPACE: {{.Values.EVENTS_FRAMEWORK_ENV_NAMESPACE | quote }}
  ACCESS_CONTROL_SERVICE_BASEPATH: {{.Values.ACCESS_CONTROL_SERVICE_BASEPATH | quote }}
  ACCESS_CONTROL_SERVICE_HOST: {{.Values.ACCESS_CONTROL_SERVICE_HOST | quote }}
  PLATFORM_SERVICE_URL: {{.Values.PLATFORM_SERVICE_URL | quote }}
  PLATFORM_SERVICE_SKIPSECUREVERIFY: {{.Values.PLATFORM_SERVICE_SKIPSECUREVERIFY | quote }}
  DROP_ALL_INDEXES_ONCE: {{.Values.DROP_ALL_INDEXES_ONCE | quote}}
  GITOPS_SERVICE_TIMESCALE_CERT_PATH: {{.Values.GITOPS_SERVICE_TIMESCALE_CERT_PATH | quote}}
  GITOPS_SERVICE_TIMESCALE_USE_TLS: {{.Values.GITOPS_SERVICE_TIMESCALE_USE_TLS}}
  GITOPS_SERVICE_TASK_LONG_POLLING: {{.Values.GITOPS_SERVICE_TASK_LONG_POLLING}}
  ENABLE_CDN: {{.Values.ENABLE_CDN}}