{{- if .Values.global.istio.enabled }}
{{- $fullName := include "gitops.fullname" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harness-gitops
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  gateways:
    {{- if .Values.global.istio.gateway.create }}
    - istio-system/public
    {{- else }}
    {{- range .Values.global.istio.virtualService.gateways }}
    - {{ . }}
    {{- end }}
    {{- end }}
  hosts:
    {{- range .Values.global.istio.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  http:
  - name: gitops
    match:
    - uri:
        prefix: /gitops/
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: {{ .Values.service.httpServerPort }}
        host: {{ $fullName }}
{{ end }}
