apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops-remote
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-remote
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: gitops-remote
roleRef:
  kind: Role
  name: gitops-remote
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-remote
  namespace: {{ .Release.Namespace }}
