apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-remote
  namespace: kube-system
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-remote
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: gitops-remote
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: gitops-remote
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-remote
  namespace: kube-system